#
#Implement this pair of service containers using docker-compose:
#  docker run -d -ti -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name odoo-db0 postgres:9.4
#  docker run --rm -ti --link odoo-db0:db --name odoo adhoc/odoo:9.0 -- -i account -d odoo --stop-after-init

version: '2'

services:

  odoo-erp0:
    image: newodoo
    #command: -- -i account -d odoo --stop-after-init
    links:
      - odoo-db0:db
    entrypoint: ./wait-for-it.sh db:5432 -- "sudo -u odoo /entrypoint.sh -- -i account -d odoo --stop-after-init"

  odoo-db0:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
